language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t robertandrei/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true robertandrei/docker-react npm run test